[package]
name = "poker-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Solve strategies, store them as blueprints, and query them."

[[bin]]
name = "poker"
path = "src/main.rs"

[dependencies]
poker-core = { path = "../poker-core" }
poker-vision = { path = "../poker-vision" }

[target.'cfg(windows)'.dependencies]
poker-win = { path = "../poker-win" }
